name: unify
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    networks:
      - intranet
    env_file:
      - stack.env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "29013:5432"

  bot:
    image: ghcr.io/lavylavenderr/unify-support:latest
    container_name: bot
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    networks:
      - intranet
    env_file:
      - stack.env
    command: >
      sh -c "pnpm run drizzle:migrate && pnpm run start"
    depends_on:
      - postgres

volumes:
  postgresdata:

networks:
  intranet:
    driver: bridge
