name: Publish to GitHub Packages

on:
  push:
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Login to GitHub Docker Repo
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u lavylavenderr --password-stdin

      - name: Build Docker Image
        run: docker build -t unify-support .

      - name: Tag Docker Image
        run: docker tag unify-support ghcr.io/lavylavenderr/unify-support:latest

      - name: Push Docker Image
        run: docker push ghcr.io/lavylavenderr/unify-support:latest
